# Generated by Django 6.1.1 on 2026-09-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('staff_type', models.CharField(choices=[('SECURITY', 'Security'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance'), ('GARDENER', 'Gardener'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
